const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["assets/vendor-Cv8FS08O.js","assets/vendor-AL2zCFOW.css"])))=>i.map(i=>d[i]);
import{a as b,S as q}from"./assets/vendor-Cv8FS08O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&l(r)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const $="47380023-0cf9eda8f68e611c05b08262c",O="https://pixabay.com/api/";async function p(e,n=1,i=12){const l={key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:n};try{return(await b.get(O,{params:l})).data}catch(t){throw console.error("Error fetching images:",t),t}}const R="modulepreload",A=function(e){return"/goit-js-hw-11/"+e},m={},y=function(n,i,l){let t=Promise.resolve();if(i&&i.length>0){document.getElementsByTagName("link");const r=document.querySelector("meta[property=csp-nonce]"),s=(r==null?void 0:r.nonce)||(r==null?void 0:r.getAttribute("nonce"));t=Promise.allSettled(i.map(a=>{if(a=A(a),a in m)return;m[a]=!0;const d=a.endsWith(".css"),S=d?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${a}"]${S}`))return;const c=document.createElement("link");if(c.rel=d?"stylesheet":R,d||(c.as="script"),c.crossOrigin="",c.href=a,s&&c.setAttribute("nonce",s),document.head.appendChild(c),d)return new Promise((P,_)=>{c.addEventListener("load",P),c.addEventListener("error",()=>_(new Error(`Unable to preload CSS for ${a}`)))})}))}function o(r){const s=new Event("vite:preloadError",{cancelable:!0});if(s.payload=r,window.dispatchEvent(s),!s.defaultPrevented)throw r}return t.then(r=>{for(const s of r||[])s.status==="rejected"&&o(s.reason);return n().catch(o)})};let h;function g(e){const n=document.querySelector(".gallery"),i=e.map(({webformatURL:l,largeImageURL:t,tags:o,likes:r,views:s,comments:a,downloads:d})=>`
  <a href="${t}" class="gallery-item">
    <div class="photo-card">
      <img src="${l}" alt="${o}" />
      <div class="info">
        <div class="item"><h3>Likes</h3><p>${r}</p></div>
        <div class="item"><h3>Views</h3><p>${s}</p></div>
        <div class="item"><h3>Comments</h3><p>${a}</p></div>
        <div class="item"><h3>Downloads</h3><p>${d}</p></div>
      </div>
    </div>
  </a>
`).join("");n.insertAdjacentHTML("beforeend",i),h?h.refresh():h=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function D(){const e=document.querySelector(".gallery");e.innerHTML=""}function v(){document.querySelector("#loader").classList.remove("hidden")}function w(){document.querySelector("#loader").classList.add("hidden")}function E(){y(()=>import("./assets/vendor-Cv8FS08O.js").then(e=>e.i),__vite__mapDeps([0,1])).then(e=>{e.info({title:"No Results",message:"No images found for your search query. Please try again.",position:"topRight"})})}function L(){y(()=>import("./assets/vendor-Cv8FS08O.js").then(e=>e.i),__vite__mapDeps([0,1])).then(e=>{e.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})})}const I=document.querySelector("#search-form");document.querySelector(".gallery");let f=1,u="";I.addEventListener("submit",N);async function N(e){e.preventDefault();const n=e.target.elements.query.value.trim();if(!(!n||n===u)){u=n,f=1,D(),v();try{const i=await p(u,f);if(i.hits.length===0){E();return}g(i.hits)}catch{L()}finally{w()}}}window.addEventListener("scroll",T);async function T(){if(window.innerHeight+window.scrollY>=document.body.offsetHeight-200){f+=1,v();try{const e=await p(u,f);if(e.hits.length===0){E();return}g(e.hits)}catch{L()}finally{w()}}}
//# sourceMappingURL=index.js.map
