import{a as L,S,i as d}from"./assets/vendor-DXxYuphV.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const b="47380023-0cf9eda8f68e611c05b08262c",q="https://pixabay.com/api/";async function u(t,o=1,i=12){const s={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:o};try{return(await L.get(q,{params:s})).data}catch(e){throw console.error("Error fetching images:",e),e}}let l;function f(t){const o=document.querySelector(".gallery"),i=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:n,views:g,comments:v,downloads:w})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${s}" alt="${r}" />
        <div class="info">
          <div class="item"><h3>Likes</h3><p>${n}</p></div>
          <div class="item"><h3>Views</h3><p>${g}</p></div>
          <div class="item"><h3>Comments</h3><p>${v}</p></div>
          <div class="item"><h3>Downloads</h3><p>${w}</p></div>
        </div>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",i),l?l.refresh():l=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function E(){const t=document.querySelector(".gallery");t.innerHTML=""}function h(){document.querySelector("#loader").classList.add("visible")}function m(){document.querySelector("#loader").classList.remove("visible")}function p(){d.info({title:"No Results",message:"No images found for your search query. Please try again.",position:"topRight"})}function y(){d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}const P=document.querySelector("#search-form");document.querySelector(".gallery");let c=1,a="";P.addEventListener("submit",$);async function $(t){t.preventDefault();const o=t.target.elements.query.value.trim();if(!(!o||o===a)){a=o,c=1,E(),h();try{const i=await u(a,c);if(i.hits.length===0){p();return}f(i.hits)}catch{y()}finally{m()}}}window.addEventListener("scroll",N);async function N(){if(window.innerHeight+window.scrollY>=document.body.offsetHeight-200){c+=1,h();try{const t=await u(a,c);if(t.hits.length===0){p();return}f(t.hits)}catch{y()}finally{m()}}}
//# sourceMappingURL=index.js.map
